plugins {
    id 'java'
    id 'me.champeau.jmh' version '0.7.3'
}

group = 'net.sixik.javastructg'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform {
        excludeTags 'benchmark'
    }
}

tasks.register('benchmarkTest', Test) {
    description = 'Runs microbenchmarks for NativeArray.'
    group = 'verification'
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath

    useJUnitPlatform {
        includeTags 'benchmark'
    }

    shouldRunAfter test

    testLogging {
        showStandardStreams = true
    }
}

jmh {
    jmhVersion = '1.37'
    warmupIterations = 3
    iterations = 5
    fork = 1
    resultFormat = 'JSON'
    resultsFile = layout.buildDirectory.file('reports/jmh/results.json').get().asFile
    humanOutputFile = layout.buildDirectory.file('reports/jmh/human.txt').get().asFile
}
